add profile-page
Yandex-12-Team007/2048 pull request #5
Opened 2022-04-09 09:46 UTC by AsenchikA

2022-04-09 14:03 UTC, RotLenin reviewed
Думаю большинство проблем уйдет с переходом на react-hook-form + yup. Так же настоятельно рекомендую разбить это дело на 3 Роута

2022-04-09 14:03 UTC, RotLenin commented on src/App.tsx
> +const Profile = lazy(() => import('Pages/profile/Profile'));
Делай index.tsx в папке тогда путь будет короче + лучше именовать папку с большой буквы. тогда будет совпадение названия страницы и import что есть гуд. + получаем промежуточную точку index.tsx что крайне часто спасает при изменении ТЗ от заказчика )

2022-04-09 14:03 UTC, RotLenin commented on src/components/Button/Button.tsx
> +      className={classNames('button', getClassNameByAppearance(), className)}
Имхо, выглядит замудренно и не понятно зачем ) можно сделать например так :

`
const btnTypeClass = types[appearance] ?? ''; 
classNames('button', className, btnTypeClass)
`

2022-04-09 14:03 UTC, RotLenin commented on src/components/Button/Button.tsx
> +export default Button;
В целом на кнопку крайне часто вешается action, etc, думаю в дальнейшем было бы круто сделать компонент более универсальным, но на текущий момент не критично

2022-04-09 14:03 UTC, RotLenin commented on src/components/TextInput/TextInput.tsx
> +const TextInput: React.FunctionComponent<ITextInputProps> = ({className, type, value, onChange}) => {
TextInput принимает type )) Судя по названию он должен быть всегда text)
+ не очень понимаю обьявление через React.FunctionComponent, у нас и так идет импорт React, можно сделать например так :

`import React, {ChangeEvent, FunctionComponent}; const TextInput : FunctionalComponent<> ...`

2022-04-09 14:03 UTC, RotLenin commented on src/pages/profile/Profile.tsx
> +export default function Profile() {
Имхо, это 3 разные экранные формы, интуитивно понятнее сделать 3 Роута и 1 обертку Profile

каждый Роут пробрасывает в Profile свои свойства. И далее проще будет со всем этим делом работать )

Все они в конечном счете берут свойства из Хранилища (да да, которое мы подключим на следующих спринтах, а пока терпим =) )

2022-04-09 14:03 UTC, RotLenin commented on src/pages/profile/components/password-info-editing/PasswordInfoEditing.pcss
> +  &__list {
А ЧТО ТАК МОЖНО БЫЛО ? О_о )))

2022-04-09 14:03 UTC, RotLenin commented on src/pages/profile/components/password-info-editing/PasswordInfoEditing.tsx
> +const PasswordInfoEditing: React.FunctionComponent<IPasswordInfoEditingProps> = ({ onSave }) => {
Смотри коменты выше =) + Сюда бы общий движок, т.к. задачи +- одни и те же

2022-04-09 16:17 UTC, AsenchikA commented on src/components/TextInput/TextInput.tsx
> +const TextInput: React.FunctionComponent<ITextInputProps> = ({className, type, value, onChange}) => {
да, с type для textinput получилось забавно)) видно, что добавился уже в процессе))
с FunctionComponent согласна тоже

2022-04-09 16:17 UTC, AsenchikA commented on src/pages/profile/components/password-info-editing/PasswordInfoEditing.pcss
> +  &__list {
дивный новый мир)))

2022-04-11 15:38 UTC, RotLenin commented on src/pages/profile/components/password-info-editing/PasswordInfoEditing.tsx
> +  oldPassword: string().required('Укажите значение'),
По паролям лучше добавить требования с прошлых спринтов, 1 заглавная и тд, у yup можно прокинуть размер, регулярки и тд :
https://github.com/jquense/yup
string.matches полагаю

Но думаю для текущего пула это не проблема

2022-04-11 15:38 UTC, RotLenin commented on src/pages/profile/index.tsx
> +export default function Profile(props) {
А что мешает сделать 3 разные входные точки ? =)

2022-04-11 15:38 UTC, RotLenin commented on src/components/Button/Button.tsx
> -export enum EButtonAppearance {
Очередная тема для Холивара E - перед Enum ) думаю решим все вопросы при созвоне с куратором )

2022-04-11 19:37 UTC, AsenchikA commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница пользователя](https://trello.com/c/xEDnVx5g/23-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F)

2022-04-12 14:46 UTC, bercly0b commented on package.json
> +    "yup": "0.32.11"
зависимости, которые используются в рантайме нужно перенести в `dependencies`
в `devDependencies` - то, что используется для сборки, тестирования, типы и тд

2022-04-12 14:47 UTC, bercly0b commented on src/pages/profile/components/profile-info/ProfileInfo.tsx
> +          <span className='profile-info__item-caption'>Почта</span>
а почему classnames не используешь, который установлен в этом ПР?)
удобнее же, чем руками писать

2022-04-12 14:48 UTC, bercly0b requested changes
ну и по поводу роутов для страницы `Profile` на синке обсудили

2022-04-13 06:36 UTC, bercly0b commented on src/pages/profile/Profile.tsx
> +        onPasswordChange={() => setCurrentView(CurrentView.PROFILE_PASSWORD_EDITING)}
вот такое точно нужно в `useCallback` оборачивать)

2022-04-13 06:38 UTC, bercly0b commented on src/pages/profile/Profile.tsx
> +        {renderInfo()}
я бы наверное вместо функций сделал что то типо
```
{currentView === CurrentView.PROFILE_INFO && (
 <ProfileInfo
        onInfoChange={() => setCurrentView(CurrentView.PROFILE_EDITING)}
        onPasswordChange={() => setCurrentView(CurrentView.PROFILE_PASSWORD_EDITING)}
/>
)}
```

кажется так читаемость будет получше. хотя вкусовщина..

2022-04-13 06:39 UTC, bercly0b approved these changes

2022-04-13 17:14 UTC, merged