Add error boundary
Yandex-12-Team007/2048 pull request #6
Opened 2022-04-09 12:56 UTC by RotLenin

Обработчик ошибок. Пока разбираюсь как лучше. Честно говоря думал что ошибка будет заменять только компонент в котором сработала.... Но почему то всплывает до самого верха ._.

2022-04-09 16:14 UTC, AsenchikA commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +    // Обновление состояния, чтобы при последующей отрисовке показать аварийный UI.
а нам точно нужен этот комментарий?) ну и вывод в консоль наверное лишний, если в `componentDidCatch` есть, ещё и с подробностями ошибки

2022-04-09 16:14 UTC, AsenchikA commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +    // @ts-ignore
а на что здесь ts ругается?

2022-04-09 16:14 UTC, AsenchikA commented on src/components/Footer/Footer.tsx
> +  return <ErrorBoundary>
а можно просто весь App обернуть вместо каждого роута?

2022-04-11 12:34 UTC, RotLenin commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +    // @ts-ignore
TS2339: Property 'hasError' does not exist on type 'Readonly{}>'.

2022-04-11 12:35 UTC, RotLenin commented on src/components/Footer/Footer.tsx
> +  return <ErrorBoundary>
Смысл в том, чтобы ошибка закрывала только компонент с ошибкой, например только profileWiget. А страница продолжала работать, если ошибка в каком то не значительном компоненте

2022-04-11 15:08 UTC, bercly0b commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +    // @ts-ignore
ну надо починить) 
подскзка - в `React.Component` можно передавать интерфейсы

2022-04-11 15:08 UTC, bercly0b commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +  }
давай удалим `componentDidCatch`, раз он не используется?

2022-04-11 15:09 UTC, bercly0b commented on src/components/Nav/Nav.tsx
> +  throw new Error('Возникли ошибки');
это наверное лишнее)

2022-04-11 15:09 UTC, bercly0b requested changes
есть вопросы

2022-04-11 15:39 UTC, RotLenin commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +  }
Окей

2022-04-12 13:53 UTC, bercly0b approved these changes

2022-04-13 06:52 UTC, merged